[package]
name = "ktar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ktar-lib = { path = "crates/ktar_lib" }

[dependencies.clap]
version = "3.2.17"
features = [ "derive" ]